name: Hello World
author: Alexandre
description: My First Git Action
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: Alex
outputs:
  time:
    description: 'The greeting time'
runs:
  using: 'node12'
  main: 'dist/index.js'