name: Test
on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send a Slack Message
        uses: ./.github/actions/slack
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          message: Hello Slack 
      - uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Title
          body: Body
          assignees: |
            marodrigues20
      - run: |
          echo ${{ steps.issue.outputs.issue }}
      #- uses: ./.github/actions/hello
      #  id: hello
      #  with:
      #    who-to-greet: "World"
      - uses: ./.github/actions/hello-docker/
        id: hello
        with:
          who-to-greet: "World"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo $HELLO 
